from tkinter import*
m=Tk()
m.geometry('320x380')
m.title('Calculator')
f1=Frame(m,bg='light pink')
f1.pack(side=TOP,fill=X)
f2=Frame(m,bg='light pink')
f2.pack(anchor=NW,fill=X)
def numclick(num):
    current = t.get('1.0','end-1c')
    t.delete(0.0,END)
    t.insert(0.0,str(current)+str(num))
def clear():
    t.delete('1.0','end-1c')
def delete():
    t.delete('end-2c','end-1c')
def ans():
    v=t.get('1.0','end-1c')
    res=eval(v)
    t.insert(END,'=')
    t.insert(END,res)
t=Text(f1,bg='light green',font='italic 12 bold',height=4,borderwidth=3)
t.pack(fill=X)
Button(f2,text='1',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(1),borderwidth=3).grid(row=0,column=0)
Button(f2,text='2',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(2),borderwidth=3).grid(row=0,column=1)
Button(f2,text='3',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(3),borderwidth=3).grid(row=0,column=2)
Button(f2,text='4',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(4),borderwidth=3).grid(row=1,column=0)
Button(f2,text='5',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(5),borderwidth=3).grid(row=1,column=1)
Button(f2,text='6',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(6),borderwidth=3).grid(row=1,column=2)
Button(f2,text='7',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(7),borderwidth=3).grid(row=2,column=0)
Button(f2,text='8',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(8),borderwidth=3).grid(row=2,column=1)
Button(f2,text='9',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(9),borderwidth=3).grid(row=2,column=2)
Button(f2,text='0',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick(0),borderwidth=3).grid(row=3,column=0)
Button(f2,text='+',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick("+"),borderwidth=3).grid(row=0,column=3)
Button(f2,text='-',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick("-"),borderwidth=3).grid(row=1,column=3)
Button(f2,text='*',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick("*"),borderwidth=3).grid(row=2,column=3)
Button(f2,text='%',bg='cyan',fg='white',width=8,height=4,command=lambda:numclick("%"),borderwidth=3).grid(row=3,column=3)
Button(f2,text='cl',bg='cyan',fg='white',width=8,height=4,command=clear,borderwidth=3).grid(row=3,column=2)
Button(f2,text='del',bg='cyan',fg='white',width=8,height=4,command=delete,borderwidth=3).grid(row=3,column=1)
Button(f2,text='=',bg='cyan',fg='white',width=5,height=20,command=ans,borderwidth=3).grid(row=0,column=4,rowspan=4)
m.mainloop()